"""SolidWorks COM execution adapter.

Drives SolidWorks headlessly via subprocess-isolated Python scripts using
``win32com.client``.  Each run spawns a fresh ``python.exe`` process that
dispatches ``SldWorks.Application``, executes the provided COM script, and
writes geometry artifacts (STEP/STL) plus a manifest JSON.

The adapter follows the same pattern as :class:`SpaceClaimRunner` but targets
SolidWorks via its COM automation interface instead of SpaceClaim's script API.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

_LARGE_PENALTY = 1.0e9


class SolidWorksRunner:
    """Execute SolidWorks COM scripts in isolated subprocesses."""

    def __init__(
        self,
        python_executable: Optional[str] = None,
        timeout: float = 900.0,
    ) -> None:
        self.timeout = timeout
        self.python_executable = python_executable or sys.executable
        self._available = self._detect_solidworks()

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    @staticmethod
    def _detect_solidworks() -> bool:
        """Detect SolidWorks via the ``SOLIDWORKS_EXE`` env var or Windows registry.

        Checks (in order):
        1. ``SOLIDWORKS_EXE`` environment variable pointing to an existing file.
        2. Windows registry for the ``SldWorks.Application`` ProgID under
           ``HKEY_CLASSES_ROOT`` or ``HKEY_LOCAL_MACHINE``.

        Returns ``True`` if SolidWorks is detected.
        """
        env = os.environ.get("SOLIDWORKS_EXE")
        if env and Path(env).exists():
            return True

        try:
            import winreg

            for hive in (winreg.HKEY_CLASSES_ROOT, winreg.HKEY_LOCAL_MACHINE):
                for subkey in (
                    "SldWorks.Application",
                    r"SOFTWARE\Classes\SldWorks.Application",
                ):
                    try:
                        with winreg.OpenKey(hive, subkey):
                            return True
                    except OSError:
                        continue
        except ImportError:
            # winreg is only available on Windows
            pass

        return False

    @property
    def available(self) -> bool:
        """Return ``True`` if SolidWorks was detected on this machine."""
        return self._available

    # ------------------------------------------------------------------
    # Preflight
    # ------------------------------------------------------------------

    @staticmethod
    def _render_preflight_script(marker_path: Path) -> str:
        """Render a self-contained Python script that tests the SolidWorks COM connection.

        The generated script:
        1. Tries to import ``win32com.client``.
        2. Dispatches ``SldWorks.Application`` with ``Visible = False``.
        3. Attempts to create a new part document using the default template.
        4. Closes the document and exits SolidWorks.
        5. Writes a JSON marker file with the result (always, even on failure).
        """
        lines: List[str] = [
            '# -*- coding: utf-8 -*-',
            '"""SolidWorks preflight check -- generated by ThermalForge."""',
            'import json',
            'import sys',
            'import traceback',
            '',
            f'marker_path = {str(marker_path)!r}',
            '',
            'def _write_marker(result):',
            '    try:',
            '        with open(marker_path, "w", encoding="utf-8") as _f:',
            '            json.dump(result, _f, indent=2)',
            '    except Exception:',
            '        pass',
            '',
            'result = {"ok": False, "reason": "not started"}',
            '',
            'try:',
            '    import win32com.client',
            'except ImportError:',
            '    _write_marker({"ok": False, "reason": "pywin32 (win32com) is not installed in the subprocess Python"})',
            '    sys.exit(1)',
            '',
            'sw_app = None',
            'try:',
            '    sw_app = win32com.client.Dispatch("SldWorks.Application")',
            '    sw_app.Visible = False',
            '',
            '    doc_created = False',
            '    doc_title = None',
            '    try:',
            '        # swDefaultTemplatePart = 7',
            '        template = sw_app.GetUserPreferenceStringValue(7)',
            '        if template and str(template).strip():',
            '            model = sw_app.NewDocument(template, 0, 0, 0)',
            '            if model is not None:',
            '                doc_created = True',
            '                doc_title = model.GetTitle()',
            '    except Exception:',
            '        pass',
            '',
            '    if doc_title:',
            '        try:',
            '            sw_app.CloseDoc(doc_title)',
            '        except Exception:',
            '            pass',
            '',
            '    result = {',
            '        "ok": True,',
            '        "reason": "SolidWorks COM connection and basic document operations successful",',
            '        "doc_created": doc_created,',
            '    }',
            'except Exception as exc:',
            '    result = {',
            '        "ok": False,',
            '        "reason": "COM dispatch failed: " + str(exc),',
            '        "error_type": type(exc).__name__,',
            '        "traceback": traceback.format_exc()[-500:],',
            '    }',
            'finally:',
            '    if sw_app is not None:',
            '        try:',
            '            sw_app.ExitApp()',
            '        except Exception:',
            '            pass',
            '    _write_marker(result)',
        ]
        return "\n".join(lines) + "\n"

    def preflight(self, timeout: float = 60.0) -> Dict[str, Any]:
        """Run a preflight check to verify that SolidWorks COM automation works.

        Returns a dict with at least ``ok`` (bool) and ``reason`` (str).
        """
        if not self._available:
            return {"ok": False, "reason": "SolidWorks not detected"}

        tmp_dir = Path(tempfile.gettempdir())
        marker = tmp_dir / f"tf_sw_preflight_marker_{os.getpid()}.json"
        script = tmp_dir / f"tf_sw_preflight_{os.getpid()}.py"
        marker.unlink(missing_ok=True)
        script.write_text(
            self._render_preflight_script(marker),
            encoding="utf-8",
            newline="\n",
        )

        proc: Optional[subprocess.CompletedProcess[str]] = None
        try:
            proc = subprocess.run(
                [self.python_executable, str(script)],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            return {"ok": False, "reason": f"Preflight timed out after {timeout}s"}
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "reason": f"Execution exception: {exc}"}
        finally:
            script.unlink(missing_ok=True)

        if not marker.exists():
            stderr = (proc.stderr or "")[-500:] if proc else ""
            return {
                "ok": False,
                "reason": "Preflight did not produce a marker file",
                "stderr": stderr,
                "stdout": (proc.stdout or "")[-500:] if proc else "",
            }

        try:
            with open(marker, "r", encoding="utf-8") as f:
                result: Dict[str, Any] = json.load(f)
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "reason": f"Failed to read marker: {exc}"}
        finally:
            marker.unlink(missing_ok=True)

        # Augment with subprocess output for diagnostics
        if proc:
            result.setdefault("stdout", (proc.stdout or "")[-500:])
            result.setdefault("stderr", (proc.stderr or "")[-500:])

        return result

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------

    def run(self, script_path: str) -> Dict[str, Any]:
        """Execute a SolidWorks COM script and wait for STEP + manifest output.

        Returns a dict with keys: ``available``, ``status``, ``step_path``,
        ``stl_path``, ``manifest_path``, ``error``, ``stdout``.
        """
        if not self._available:
            return {
                "available": False,
                "status": "skipped",
                "step_path": None,
                "stl_path": None,
                "manifest_path": None,
                "error": "SolidWorks not detected, skipping execution",
                "stdout": "",
                "penalty": _LARGE_PENALTY,
            }

        script = Path(script_path).resolve()
        if not script.exists():
            return {
                "available": True,
                "status": "invalid_geometry",
                "step_path": None,
                "stl_path": None,
                "manifest_path": None,
                "error": f"Script does not exist: {script_path}",
                "stdout": "",
                "penalty": _LARGE_PENALTY,
            }

        step_path = script.with_suffix(".stp")
        stl_path = script.with_suffix(".stl")
        manifest_path = script.with_suffix(".json")
        for old in (step_path, stl_path, manifest_path):
            old.unlink(missing_ok=True)

        proc: Optional[subprocess.CompletedProcess[str]] = None
        try:
            proc = subprocess.run(
                [self.python_executable, str(script)],
                capture_output=True,
                text=True,
                timeout=self.timeout,
            )
        except subprocess.TimeoutExpired:
            return {
                "available": True,
                "status": "error",
                "step_path": None,
                "stl_path": None,
                "manifest_path": None,
                "error": f"SolidWorks script timed out after {self.timeout}s",
                "stdout": "",
                "penalty": _LARGE_PENALTY,
            }
        except Exception as exc:  # noqa: BLE001
            return {
                "available": True,
                "status": "error",
                "step_path": None,
                "stl_path": None,
                "manifest_path": None,
                "error": f"Execution exception: {exc}",
                "stdout": "",
                "penalty": _LARGE_PENALTY,
            }

        stdout = (proc.stdout or "")[-1000:]
        stderr = (proc.stderr or "")[-1000:]

        manifest_ok = manifest_path.exists() and manifest_path.stat().st_size > 0
        step_ok = step_path.exists() and step_path.stat().st_size > 0
        stl_ok = stl_path.exists() and stl_path.stat().st_size > 0

        # No manifest at all -- the script failed catastrophically
        if not manifest_ok:
            return {
                "available": True,
                "status": "invalid_geometry",
                "step_path": str(step_path) if step_ok else None,
                "stl_path": str(stl_path) if stl_ok else None,
                "manifest_path": None,
                "error": "Script did not produce a manifest",
                "stdout": stdout,
                "stderr": stderr,
                "penalty": _LARGE_PENALTY,
            }

        # Read manifest to check for script-reported errors
        manifest_data: Dict[str, Any] = {}
        try:
            with open(manifest_path, "r", encoding="utf-8") as f:
                manifest_data = json.load(f)
        except Exception:  # noqa: BLE001
            pass

        manifest_status = str(manifest_data.get("status", "")).lower()

        # Manifest reports an error
        if manifest_status in ("error", "failed"):
            return {
                "available": True,
                "status": "invalid_geometry",
                "step_path": str(step_path) if step_ok else None,
                "stl_path": str(stl_path) if stl_ok else None,
                "manifest_path": str(manifest_path),
                "error": manifest_data.get(
                    "error", "Script reported an error in manifest"
                ),
                "stdout": stdout,
                "stderr": stderr,
                "penalty": _LARGE_PENALTY,
            }

        # Non-zero return code but manifest exists -- execution error
        if proc.returncode not in (0, None):
            return {
                "available": True,
                "status": "error",
                "step_path": str(step_path) if step_ok else None,
                "stl_path": str(stl_path) if stl_ok else None,
                "manifest_path": str(manifest_path),
                "error": f"Script returned non-zero exit code: {proc.returncode}",
                "stdout": stdout,
                "stderr": stderr,
                "penalty": _LARGE_PENALTY,
            }

        # STEP file is the primary geometry artifact
        if not step_ok:
            return {
                "available": True,
                "status": "invalid_geometry",
                "step_path": None,
                "stl_path": str(stl_path) if stl_ok else None,
                "manifest_path": str(manifest_path),
                "error": "Script did not produce a valid STEP file",
                "stdout": stdout,
                "stderr": stderr,
                "penalty": _LARGE_PENALTY,
            }

        return {
            "available": True,
            "status": "ok",
            "step_path": str(step_path),
            "stl_path": str(stl_path) if stl_ok else None,
            "manifest_path": str(manifest_path),
            "error": None,
            "stdout": stdout,
            "penalty": 0.0,
        }
