"""Render Python COM scripts from SolidWorks optimization contracts.

The :class:`SolidWorksScriptRenderer` consumes a
:class:`~core.models.optimization.SolidWorksOptimizationContract` and produces
a standalone Python script that can be executed by ``python script.py``.
The script connects to SolidWorks via ``win32com.client``, imports the source
model, applies each operation, exports STEP/STL geometry, generates preview
images, and writes a manifest JSON.
"""
from __future__ import annotations

import json
import math
import os
import textwrap
from pathlib import Path
from typing import Any, Dict, List

from ..models.optimization import SolidWorksOptimizationContract


class SolidWorksScriptRenderer:
    """Render executable SolidWorks COM scripts from optimization contracts."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render(self, contract: SolidWorksOptimizationContract) -> str:
        """Render a complete Python COM script for the given contract.

        The returned string is valid Python that can be saved to a ``.py``
        file and executed via ``python <script>.py``.
        """
        contract_json = json.dumps(
            contract.model_dump(mode="json"),
            ensure_ascii=False,
            indent=2,
        )

        # Build operation execution blocks
        op_blocks: List[str] = []
        for idx, instruction in enumerate(contract.operations):
            op_dict = instruction.model_dump(mode="json")
            op_type = op_dict.get("operation_type", "unknown")
            lines = self._render_operation(idx, op_dict)
            block_lines: List[str] = [
                f"# --- Operation {idx}: {op_type} ---",
                f"_op = _operations_data[{idx}]",
                "try:",
                f'    print("Executing operation {idx}: " + _op.get("operation_type", "unknown"))',
            ]
            for line in lines:
                if line.strip():
                    block_lines.append(f"    {line}")
                else:
                    block_lines.append("")
            block_lines.extend([
                f'except Exception as _op_exc:',
                f'    print("Operation {idx} failed: " + str(_op_exc))',
                f'    _op_errors.append({{"index": {idx}, "type": "{op_type}", "error": str(_op_exc)}})',
                "",
            ])
            op_blocks.append("\n".join(block_lines))

        operations_code = "\n".join(op_blocks)
        # Indent to 8 spaces to match the body of main()'s outer try block
        operations_code = textwrap.indent(operations_code, "        ")
        multi_view = contract.output_plan.multi_view
        geometry_formats = list(contract.output_plan.geometry_formats)

        script = f'''# -*- coding: utf-8 -*-
"""SolidWorks COM script -- generated by ThermalForge SolidWorksScriptRenderer.

Contract ID: {contract.id}
Pipeline:    {contract.pipeline_id}
Iteration:   {contract.iteration}
"""
import json
import math
import os
import sys
import traceback

# ── Embedded contract ──────────────────────────────────────────────
_CONTRACT = json.loads({contract_json!r})

def _write_manifest(path, manifest):
    """Write manifest JSON, swallowing errors so we always exit cleanly."""
    try:
        with open(path, "w", encoding="utf-8") as _f:
            json.dump(manifest, _f, indent=2, ensure_ascii=False)
    except Exception:
        pass

def main():
    contract = _CONTRACT
    iteration = contract["iteration"]
    source_model_uri = contract["source_model_uri"]
    source_format = contract["source_format"]
    output_plan = contract["output_plan"]
    workspace_dir = output_plan["workspace_dir"]

    # Derive output paths from this script's location so the runner can
    # find them via script.with_suffix(".stp") etc.
    _script_path = os.path.abspath(__file__)
    _script_stem = os.path.splitext(_script_path)[0]
    _script_dir = os.path.dirname(_script_path)

    step_path = _script_stem + ".stp"
    stl_path = _script_stem + ".stl"
    manifest_path = _script_stem + ".json"

    geometry_formats = {geometry_formats!r}
    multi_view = {multi_view!r}

    _operations_data = contract["operations"]
    _op_errors = []

    manifest = {{
        "status": "error",
        "iteration": iteration,
        "contract_id": contract.get("id", ""),
        "step_path": None,
        "stl_path": None,
        "preview_paths": [],
        "operation_errors": [],
        "error": None,
    }}

    # ── Import win32com ─────────────────────────────────────────────
    try:
        import win32com.client
    except ImportError:
        manifest["error"] = "pywin32 (win32com) is not installed in the subprocess Python"
        _write_manifest(manifest_path, manifest)
        print("ERROR: " + manifest["error"], file=sys.stderr)
        sys.exit(1)

    sw_app = None
    model = None
    try:
        # ── Connect to SolidWorks ──────────────────────────────────
        sw_app = win32com.client.Dispatch("SldWorks.Application")
        sw_app.Visible = False
        sw_app.UserControl = False

        # ── Import source model ────────────────────────────────────
        # swDocPART = 1, swDocASSEMBLY = 2
        # swOpenDocOptions_Silent = 1
        _doc_type = 1  # part
        if source_format == "step":
            # Try LoadFile4 (preferred for foreign formats), fall back to OpenDoc6
            try:
                model = sw_app.LoadFile4(source_model_uri, "", 0)
            except Exception:
                model = None
            if model is None:
                try:
                    model = sw_app.OpenDoc6(source_model_uri, _doc_type, 1, "", 0, 0)
                except Exception:
                    model = None
        elif source_format == "stl":
            try:
                model = sw_app.LoadFile4(source_model_uri, "", 0)
            except Exception:
                model = None
            if model is None:
                try:
                    model = sw_app.OpenDoc6(source_model_uri, _doc_type, 1, "", 0, 0)
                except Exception:
                    model = None
        else:
            manifest["error"] = "Unsupported source format: " + str(source_format)
            _write_manifest(manifest_path, manifest)
            sys.exit(1)

        if model is None:
            manifest["error"] = "Failed to import source model: " + str(source_model_uri)
            _write_manifest(manifest_path, manifest)
            sys.exit(1)

        # Force a rebuild to ensure all features are up to date
        try:
            model.ForceRebuild3(False)
        except Exception:
            pass

        # ── Execute operations ──────────────────────────────────────
{operations_code}

        # Record operation errors in manifest
        if _op_errors:
            manifest["operation_errors"] = _op_errors

        # ── Export STEP ─────────────────────────────────────────────
        if "step" in geometry_formats:
            try:
                _errors = 0
                _warnings = 0
                model.Extension.SaveAs(step_path, 0, 0, None, _errors, _warnings)
                manifest["step_path"] = step_path
            except Exception as _export_exc:
                # Fallback to model.SaveAs
                try:
                    model.SaveAs(step_path, 0, 0, 0)
                    manifest["step_path"] = step_path
                except Exception:
                    manifest["error"] = "STEP export failed: " + str(_export_exc)

        # ── Export STL ──────────────────────────────────────────────
        if "stl" in geometry_formats:
            try:
                _errors = 0
                _warnings = 0
                model.Extension.SaveAs(stl_path, 0, 0, None, _errors, _warnings)
                manifest["stl_path"] = stl_path
            except Exception as _export_exc:
                try:
                    model.SaveAs(stl_path, 0, 0, 0)
                    manifest["stl_path"] = stl_path
                except Exception:
                    # STL is secondary; don't fail the whole run
                    pass

        # ── Generate multi-view preview images ──────────────────────
        if multi_view:
            _preview_paths = []
            _views = [
                (1, "front"),       # swFrontView
                (5, "top"),         # swTopView
                (7, "isometric"),   # swIsometricView
                (4, "right"),       # swRightView
                (3, "left"),        # swLeftView
                (2, "back"),        # swBackView
            ]
            for _view_id, _view_name in _views:
                try:
                    model.ShowNamedView2("", _view_id)
                    _preview_path = os.path.join(_script_dir, "preview_%d_%s.png" % (iteration, _view_name))
                    model.SaveAs(_preview_path, 0, 0, 0)
                    _preview_paths.append(_preview_path)
                except Exception:
                    pass
            manifest["preview_paths"] = _preview_paths

        # ── Finalise manifest ───────────────────────────────────────
        manifest["status"] = "ok"
        manifest["workspace_dir"] = workspace_dir
        manifest["source_model_uri"] = source_model_uri

    except Exception as exc:
        manifest["status"] = "error"
        manifest["error"] = type(exc).__name__ + ": " + str(exc)
        manifest["traceback"] = traceback.format_exc()[-1000:]
    finally:
        if model is not None:
            try:
                sw_app.CloseDoc(model.GetTitle())
            except Exception:
                pass
        if sw_app is not None:
            try:
                sw_app.ExitApp()
            except Exception:
                pass
        _write_manifest(manifest_path, manifest)

if __name__ == "__main__":
    main()
'''
        return script

    # ------------------------------------------------------------------
    # Operation rendering
    # ------------------------------------------------------------------

    def _render_operation(self, idx: int, op: dict) -> list[str]:
        """Render COM API code lines for a single operation.

        Parameters
        ----------
        idx
            Zero-based operation index (used for diagnostics).
        op
            Operation dict with keys ``operation_type``, ``target_component``,
            ``parameters``, and ``rationale``.

        Returns
        -------
        list[str]
            Python code lines (without leading try-block indentation).
            Nested blocks use their own relative indentation.
        """
        op_type = op.get("operation_type", "")
        params = op.get("parameters", {})
        target = op.get("target_component", "")

        dispatch = {
            "thicken_wall": self._render_thicken_wall,
            "add_cooling_fin": self._render_add_cooling_fin,
            "add_fillet": self._render_add_fillet,
            "add_chamfer": self._render_add_chamfer,
            "add_hole": self._render_add_hole,
            "modify_dimension": self._render_modify_dimension,
            "add_feature": self._render_add_feature,
            "remove_feature": self._render_remove_feature,
            "modify_sketch": self._render_modify_sketch,
            "change_appearance": self._render_change_appearance,
        }

        handler = dispatch.get(op_type)
        if handler is None:
            return [
                f'print("WARNING: unknown operation type: {op_type}")',
            ]

        return handler(params, target)

    # ------------------------------------------------------------------
    # Individual operation renderers
    # ------------------------------------------------------------------

    def _render_thicken_wall(self, params: dict, target: str) -> list[str]:
        """Render Thicken feature on a target face.

        Parameters: ``thickness`` (mm), ``target_face`` (optional, defaults
        to ``target_component``).
        """
        return [
            '_thickness_mm = float(_op.get("parameters", {}).get("thickness", 1.0))',
            '_target_face = _op.get("parameters", {}).get("target_face", _op.get("target_component", ""))',
            '_thickness_m = _thickness_mm / 1000.0',
            'model.Extension.SelectByID2(str(_target_face), "FACE", 0, 0, 0, False, 0, None, 0)',
            'model.FeatureManager.InsertFeatureThicken(_thickness_m, True, False, False, True)',
        ]

    def _render_add_cooling_fin(self, params: dict, target: str) -> list[str]:
        """Render extruded-fin creation with optional linear pattern.

        Parameters: ``fin_count``, ``fin_spacing`` (mm), ``fin_height`` (mm),
        ``fin_thickness`` (mm), ``fin_width`` (mm), ``target_face`` (optional).
        """
        return [
            '_fin_count = int(_op.get("parameters", {}).get("fin_count", 3))',
            '_fin_spacing_mm = float(_op.get("parameters", {}).get("fin_spacing", 5.0))',
            '_fin_height_mm = float(_op.get("parameters", {}).get("fin_height", 10.0))',
            '_fin_thickness_mm = float(_op.get("parameters", {}).get("fin_thickness", 2.0))',
            '_fin_width_mm = float(_op.get("parameters", {}).get("fin_width", 20.0))',
            '_target_face = _op.get("parameters", {}).get("target_face", _op.get("target_component", ""))',
            '_ft = _fin_thickness_mm / 1000.0',
            '_fw = _fin_width_mm / 1000.0',
            '_fh = _fin_height_mm / 1000.0',
            '_fs = _fin_spacing_mm / 1000.0',
            '# Select target face and open sketch',
            'model.Extension.SelectByID2(str(_target_face), "FACE", 0, 0, 0, False, 0, None, 0)',
            'model.SketchManager.InsertSketch(True)',
            'model.SketchManager.AddToDB = True',
            '# Draw fin profile rectangle (origin-based)',
            'model.SketchManager.CreateCornerRectangle(0, 0, 0, _ft, _fw, 0)',
            'model.SketchManager.AddToDB = False',
            'model.SketchManager.InsertSketch(True)',
            '# Extrude the fin',
            '_fin_feature = model.FeatureManager.FeatureExtrusion2('
            'True, False, False, 0, 0, _fh, 0, '
            'False, False, False, False, 0, 0, '
            'False, False, False, False, True, True, True, 0, 0, False)',
            '# Linear pattern for additional fins',
            'if _fin_count > 1 and _fin_feature is not None:',
            '    model.Extension.SelectByID2(_fin_feature.Name, "FEATURE", 0, 0, 0, False, 0, None, 0)',
            '    model.FeatureManager.FeatureLinearPattern('
            '_fin_count - 1, _fs, 0, 0, False, False, 0, 0, 0, 0, 0, 0)',
        ]

    def _render_add_fillet(self, params: dict, target: str) -> list[str]:
        """Render FeatureFillet3 on selected edges.

        Parameters: ``radius`` (mm), ``edges`` (optional list of edge names).
        """
        return [
            '_radius_mm = float(_op.get("parameters", {}).get("radius", 1.0))',
            '_radius_m = _radius_mm / 1000.0',
            '_edges = _op.get("parameters", {}).get("edges", [])',
            '_target = _op.get("target_component", "")',
            '# Select edges',
            'if isinstance(_edges, list) and len(_edges) > 0:',
            '    for _i, _edge in enumerate(_edges):',
            '        model.Extension.SelectByID2(str(_edge), "EDGE", 0, 0, 0, _i > 0, 0, None, 0)',
            'else:',
            '    model.Extension.SelectByID2(str(_target), "EDGE", 0, 0, 0, False, 0, None, 0)',
            '# FeatureFillet3(options, radius, ...)',
            'model.FeatureManager.FeatureFillet3('
            '195, _radius_m, 0, 0, 0, 0, 0, 0, None, None, None, None, 0, 0)',
        ]

    def _render_add_chamfer(self, params: dict, target: str) -> list[str]:
        """Render InsertFeatureChamfer on selected edges.

        Parameters: ``distance`` (mm), ``angle`` (degrees), ``edges`` (optional).
        """
        return [
            '_distance_mm = float(_op.get("parameters", {}).get("distance", 1.0))',
            '_angle_deg = float(_op.get("parameters", {}).get("angle", 45.0))',
            '_distance_m = _distance_mm / 1000.0',
            '_angle_rad = _angle_deg * math.pi / 180.0',
            '_edges = _op.get("parameters", {}).get("edges", [])',
            '_target = _op.get("target_component", "")',
            '# Select edges',
            'if isinstance(_edges, list) and len(_edges) > 0:',
            '    for _i, _edge in enumerate(_edges):',
            '        model.Extension.SelectByID2(str(_edge), "EDGE", 0, 0, 0, _i > 0, 0, None, 0)',
            'else:',
            '    model.Extension.SelectByID2(str(_target), "EDGE", 0, 0, 0, False, 0, None, 0)',
            '# InsertFeatureChamfer(options, chamferType, distance, angle, ...)',
            '# chamferType: 1 = distance-distance, 2 = distance-angle',
            'model.FeatureManager.InsertFeatureChamfer('
            '4, 2, _distance_m, _angle_rad, 0, 0, 0, 0)',
        ]

    def _render_add_hole(self, params: dict, target: str) -> list[str]:
        """Render hole creation (simple or wizard).

        Parameters: ``diameter`` (mm), ``depth`` (mm), ``pos_x`` (mm),
        ``pos_y`` (mm), ``type`` ("simple" or "wizard"), ``target_face``.
        """
        return [
            '_diameter_mm = float(_op.get("parameters", {}).get("diameter", 5.0))',
            '_depth_mm = float(_op.get("parameters", {}).get("depth", 10.0))',
            '_pos_x_mm = float(_op.get("parameters", {}).get("pos_x", 0.0))',
            '_pos_y_mm = float(_op.get("parameters", {}).get("pos_y", 0.0))',
            '_hole_type = _op.get("parameters", {}).get("type", "simple")',
            '_target_face = _op.get("parameters", {}).get("target_face", _op.get("target_component", ""))',
            '_diameter_m = _diameter_mm / 1000.0',
            '_depth_m = _depth_mm / 1000.0',
            '_pos_x_m = _pos_x_mm / 1000.0',
            '_pos_y_m = _pos_y_mm / 1000.0',
            '# Select target face and create sketch for hole position',
            'model.Extension.SelectByID2(str(_target_face), "FACE", 0, 0, 0, False, 0, None, 0)',
            'model.SketchManager.InsertSketch(True)',
            'model.SketchManager.CreatePoint(_pos_x_m, _pos_y_m, 0)',
            'model.SketchManager.InsertSketch(True)',
            'if _hole_type == "wizard":',
            '    # HoleWizard5(genericHoleType, standard, fastenerType, ...)',
            '    model.FeatureManager.HoleWizard5('
            '4, 0, 0, _diameter_m, _diameter_m, _depth_m, _depth_m, '
            '0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '
            'False, False, False, False, False, False, False)',
            'else:',
            '    # HoleSimple2(diameter, flip, depthType, depth, ...)',
            '    model.FeatureManager.HoleSimple2('
            '_diameter_m, False, False, 0, 0, _depth_m, 0, 0, 0, 0, 0, 0, 0)',
        ]

    def _render_modify_dimension(self, params: dict, target: str) -> list[str]:
        """Render dimension modification by name.

        Parameters: ``dimension_name``, ``value`` (mm).
        """
        return [
            '_dim_name = _op.get("parameters", {}).get("dimension_name", _op.get("target_component", ""))',
            '_value_mm = float(_op.get("parameters", {}).get("value", 0.0))',
            '_value_m = _value_mm / 1000.0',
            '_dim = model.Parameter(str(_dim_name))',
            'if _dim is not None:',
            '    _dim.SystemValue = _value_m',
            'else:',
            '    print("WARNING: dimension not found: " + str(_dim_name))',
            '# Rebuild to apply changes',
            'model.ForceRebuild3(False)',
        ]

    def _render_add_feature(self, params: dict, target: str) -> list[str]:
        """Render generic extrude or revolve feature.

        Parameters: ``feature_type`` ("extrude" or "revolve"), ``depth`` (mm),
        ``sketch_params`` (dict with ``shape``, ``width``, ``height``, ``radius``).
        """
        return [
            '_feature_type = _op.get("parameters", {}).get("feature_type", "extrude")',
            '_depth_mm = float(_op.get("parameters", {}).get("depth", 5.0))',
            '_sketch_params = _op.get("parameters", {}).get("sketch_params", {{}})',
            '_target = _op.get("target_component", "")',
            '_depth_m = _depth_mm / 1000.0',
            '# Select target face and open sketch',
            'model.Extension.SelectByID2(str(_target), "FACE", 0, 0, 0, False, 0, None, 0)',
            'model.SketchManager.InsertSketch(True)',
            'model.SketchManager.AddToDB = True',
            '_shape = _sketch_params.get("shape", "rectangle")',
            'if _shape == "rectangle":',
            '    _w = float(_sketch_params.get("width", 5.0)) / 1000.0',
            '    _h = float(_sketch_params.get("height", 5.0)) / 1000.0',
            '    model.SketchManager.CreateCornerRectangle(0, 0, 0, _w, _h, 0)',
            'elif _shape == "circle":',
            '    _r = float(_sketch_params.get("radius", 2.5)) / 1000.0',
            '    model.SketchManager.CreateCircle(0, 0, 0, _r, 0, 0)',
            'else:',
            '    _w = float(_sketch_params.get("width", 5.0)) / 1000.0',
            '    _h = float(_sketch_params.get("height", 5.0)) / 1000.0',
            '    model.SketchManager.CreateCornerRectangle(0, 0, 0, _w, _h, 0)',
            'model.SketchManager.AddToDB = False',
            'model.SketchManager.InsertSketch(True)',
            'if _feature_type == "revolve":',
            '    # FeatureRevolve2(singleDir, revDir, ...)',
            '    model.FeatureManager.FeatureRevolve2('
            'True, True, False, 0, 0, 2 * math.pi, 0, '
            'False, False, False, False, 0, 0, '
            'False, False, False, False, True, True, 0, 0, 0)',
            'else:',
            '    # FeatureExtrusion2(endCondition1, endCondition2, ...)',
            '    model.FeatureManager.FeatureExtrusion2('
            'True, False, False, 0, 0, _depth_m, 0, '
            'False, False, False, False, 0, 0, '
            'False, False, False, False, True, True, True, 0, 0, False)',
        ]

    def _render_remove_feature(self, params: dict, target: str) -> list[str]:
        """Render feature deletion by name.

        Parameters: ``feature_name`` (optional, defaults to ``target_component``).
        """
        return [
            '_feature_name = _op.get("parameters", {}).get("feature_name", _op.get("target_component", ""))',
            'model.Extension.SelectByID2(str(_feature_name), "FEATURE", 0, 0, 0, False, 0, None, 0)',
            'model.Extension.DeleteSelection(0)',
        ]

    def _render_modify_sketch(self, params: dict, target: str) -> list[str]:
        """Render sketch parameter modification.

        Parameters: ``sketch_name``, ``dimensions`` (dict of name -> value in mm).
        """
        return [
            '_sketch_name = _op.get("parameters", {}).get("sketch_name", _op.get("target_component", ""))',
            '_sketch_params = _op.get("parameters", {{}})',
            '# Select and edit sketch',
            'model.Extension.SelectByID2(str(_sketch_name), "SKETCH", 0, 0, 0, False, 0, None, 0)',
            'model.SketchManager.InsertSketch(True)',
            '# Modify dimensions within the sketch',
            '_dimensions = _sketch_params.get("dimensions", {{}})',
            'for _dim_name, _dim_value in _dimensions.items():',
            '    try:',
            '        _dim = model.Parameter(str(_dim_name))',
            '        if _dim is not None:',
            '            _dim.SystemValue = float(_dim_value) / 1000.0',
            '    except Exception:',
            '        pass',
            'model.SketchManager.InsertSketch(True)',
            'model.ForceRebuild3(False)',
        ]

    def _render_change_appearance(self, params: dict, target: str) -> list[str]:
        """Render material/color assignment.

        Parameters: ``material`` (optional), ``color`` (hex string or RGB list),
        ``target`` (body/component name).
        """
        return [
            '_material = _op.get("parameters", {}).get("material", "")',
            '_color = _op.get("parameters", {}).get("color", "")',
            '_target = _op.get("target_component", "")',
            '# Apply material if specified',
            'if _material:',
            '    try:',
            '        model.SetMaterialPropertyName("Default", "", str(_material))',
            '    except Exception:',
            '        pass',
            '# Apply color if specified',
            'if _color:',
            '    try:',
            '        if isinstance(_color, str) and _color.startswith("#"):',
            '            _r = int(_color[1:3], 16)',
            '            _g = int(_color[3:5], 16)',
            '            _b = int(_color[5:7], 16)',
            '        elif isinstance(_color, (list, tuple)) and len(_color) >= 3:',
            '            _r, _g, _b = int(_color[0]), int(_color[1]), int(_color[2])',
            '        else:',
            '            _r, _g, _b = 128, 128, 128',
            '        _sw_color = (_r << 16) | (_g << 8) | _b',
            '        model.Extension.SelectByID2(str(_target), "BODY", 0, 0, 0, False, 0, None, 0)',
            '        model.SetEntityColor(_sw_color, 0, 0)',
            '    except Exception:',
            '        pass',
        ]

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def write(
        self,
        contract: SolidWorksOptimizationContract,
        workspace: Path,
    ) -> Path:
        """Render the script and write it to *workspace*.

        Parameters
        ----------
        contract
            The optimization contract to render.
        workspace
            Directory where the script will be written. Created if it does
            not exist.

        Returns
        -------
        Path
            Absolute path to the written script.
        """
        workspace = Path(workspace)
        workspace.mkdir(parents=True, exist_ok=True)
        script_path = workspace / f"solidworks_contract_{contract.id}.py"
        script_path.write_text(
            self.render(contract),
            encoding="utf-8",
            newline="\n",
        )
        return script_path
